using Domain.Entities;
using Domain.Enums;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;

namespace Infrastructure
{
    public static class DbSeeder
    {
        public static async Task SeedAsync(DecorteeDbContext context)
        {
            if (await context.RoomTypes.AnyAsync())
                return;

            // Seed RoomTypes
            var roomTypes = new List<RoomType>
            {
                new() { Name = "Living Room", Description = "Main living and entertainment area", IconUrl = "/static/interior-0.jpg" },
                new() { Name = "Bedroom", Description = "Sleeping and relaxation space", IconUrl = "/static/interior-7.jpg" },
                new() { Name = "Kitchen", Description = "Cooking and meal preparation area", IconUrl = "/static/interior-8.jpg" },
                new() { Name = "Bathroom", Description = "Personal hygiene and grooming space", IconUrl = "/static/interior-3.jpg" },
                new() { Name = "Office", Description = "Work from home workspace", IconUrl = "/static/interior-4.jpg" },
                new() { Name = "Dining Room", Description = "Formal dining and gathering area", IconUrl = "/static/interior-5.jpg" }
            };
            await context.RoomTypes.AddRangeAsync(roomTypes);

            // Seed DesignStyles
            var designStyles = new List<DesignStyle>
            {
                new() { Name = "Modern", Description = "Clean lines, minimal ornamentation, and functional design", PreviewImage = "/static/interior-0.jpg" },
                new() { Name = "Minimalist", Description = "Simple, uncluttered spaces with essential elements only", PreviewImage = "/static/interior-1.jpg" },
                new() { Name = "Rustic", Description = "Natural materials, warm tones, and countryside charm", PreviewImage = "/static/interior-2.jpg" },
                new() { Name = "Industrial", Description = "Raw materials, exposed elements, and urban aesthetics", PreviewImage = "/static/interior-3.jpg" },
                new() { Name = "Scandinavian", Description = "Light colors, natural materials, and cozy simplicity", PreviewImage = "/static/interior-4.jpg" },
                new() { Name = "Traditional", Description = "Classic elegance, rich colors, and timeless appeal", PreviewImage = "/static/interior-5.jpg" }
            };
            await context.DesignStyles.AddRangeAsync(designStyles);

            // Seed sample Users
            var passwordHasher = new PasswordHasher<User>();
            var users = new List<User>
            {
                new()
                {
                    Name = "Demo User",
                    UserName = "demouser",
                    Email = "demo@decorato.com",
                    Role = Role.Customer,
                    Language = "en"
                },
                new()
                {
                    Name = "Admin User",
                    UserName = "admin",
                    Email = "admin@decorato.com",
                    Role = Role.Admin,
                    Language = "en"
                }
            };

            foreach (var user in users)
            {
                user.Password = passwordHasher.HashPassword(user, "Demo123!");
            }

            await context.Users.AddRangeAsync(users);
            await context.SaveChangesAsync();

            // Seed ShowcaseDesigns - loaded from SeederData.json (generated by download_images.py)
            var seederJsonPath = Path.Combine(AppContext.BaseDirectory, "SeederData.json");
            // fallback to source directory when running in dev
            if (!File.Exists(seederJsonPath))
                seederJsonPath = Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "../../../../Persistence/Infrastructure/SeederData.json"));

            var showcaseDesigns = new List<ShowcaseDesign>();

            if (File.Exists(seederJsonPath))
            {
                var json   = await File.ReadAllTextAsync(seederJsonPath);
                var items  = JsonSerializer.Deserialize<List<JsonElement>>(json) ?? new();

                foreach (var item in items)
                {
                    var roomName  = item.GetProperty("room").GetString()  ?? "Living Room";
                    var styleName = item.GetProperty("style").GetString() ?? "Modern";

                    var roomType   = roomTypes.FirstOrDefault(r => r.Name == roomName)   ?? roomTypes[0];
                    var styleType  = designStyles.FirstOrDefault(s => s.Name == styleName) ?? designStyles[0];
                    var idx        = item.GetProperty("index").GetInt32();
                    var userId     = (idx % 2 == 0) ? users[0].Id : users[1].Id;

                    showcaseDesigns.Add(new ShowcaseDesign
                    {
                        Title         = item.GetProperty("description").GetString() ?? $"Design #{idx}",
                        Description   = item.GetProperty("description").GetString() ?? "",
                        ImageUrl      = item.GetProperty("file").GetString() ?? $"/static/interior-{idx}.jpg",
                        RoomTypeId    = roomType.Id,
                        DesignStyleId = styleType.Id,
                        UserId        = userId,
                        IsPopular     = item.GetProperty("popular").GetBoolean(),
                        IsTrending    = item.GetProperty("trending").GetBoolean(),
                        AverageRating = item.GetProperty("rating").GetDouble(),
                        ViewCount     = item.GetProperty("views").GetInt32()
                    });
                }
            }
            else
            {
                // fallback: 50 generic designs if JSON not found
                var random = new Random(42);
                var adjectives = new[] { "Elegant", "Cozy", "Luxury", "Chic", "Serene", "Bold", "Timeless", "Fresh", "Warm", "Sleek" };
                var roomCycle  = new[] { "Living Room", "Bedroom", "Kitchen", "Bathroom", "Office", "Dining Room" };
                var styleCycle = new[] { "Modern", "Minimalist", "Rustic", "Industrial", "Scandinavian", "Traditional" };

                for (int i = 0; i < 50; i++)
                {
                    var roomType  = roomTypes.FirstOrDefault(r => r.Name == roomCycle[i % 6])   ?? roomTypes[i % roomTypes.Count];
                    var styleType = designStyles.FirstOrDefault(s => s.Name == styleCycle[i % 6]) ?? designStyles[i % designStyles.Count];
                    var ext = (i == 1 || i == 14 || i == 22) ? "png" : "jpg";
                    showcaseDesigns.Add(new ShowcaseDesign
                    {
                        Title         = $"{adjectives[i % adjectives.Length]} {roomCycle[i % 6]} Design",
                        Description   = $"A beautiful {styleCycle[i % 6].ToLower()} {roomCycle[i % 6].ToLower()} design.",
                        ImageUrl      = $"/static/interior-{i}.{ext}",
                        RoomTypeId    = roomType.Id,
                        DesignStyleId = styleType.Id,
                        UserId        = (i % 2 == 0) ? users[0].Id : users[1].Id,
                        IsPopular     = i < 10,
                        IsTrending    = i % 5 == 0,
                        AverageRating = Math.Round(random.NextDouble() * 3 + 7, 1),
                        ViewCount     = random.Next(100, 8000)
                    });
                }
            }
            await context.ShowcaseDesigns.AddRangeAsync(showcaseDesigns);

            // Seed Posts
            var posts = new List<Post>
            {
                new()
                {
                    Title = "My Living Room Transformation",
                    Content = "Just finished redesigning my living room with a modern aesthetic. The clean lines and neutral palette create such a calming atmosphere!",
                    ImageUrl = "/static/interior-40.jpg",
                    UserId = users[0].Id
                },
                new()
                {
                    Title = "Tips for Small Space Design",
                    Content = "Living in a small apartment? Here are my top tips for maximizing space while maintaining style...",
                    ImageUrl = "/static/interior-41.jpg",
                    UserId = users[0].Id
                },
                new()
                {
                    Title = "Industrial vs Modern: Which is Right for You?",
                    Content = "Comparing two popular design styles and helping you decide which fits your lifestyle better.",
                    ImageUrl = "/static/interior-42.jpg",
                    UserId = users[1].Id
                }
            };
            await context.Posts.AddRangeAsync(posts);
            await context.SaveChangesAsync();

            // Seed Comments
            var comments = new List<Comment>
            {
                new()
                {
                    PostId = posts[0].Id,
                    UserId = users[1].Id,
                    Content = "This looks amazing! What paint color did you use?"
                },
                new()
                {
                    PostId = posts[0].Id,
                    UserId = users[0].Id,
                    Content = "Thank you! It's Benjamin Moore Simply White."
                },
                new()
                {
                    PostId = posts[1].Id,
                    UserId = users[1].Id,
                    Content = "Great tips! The mirror trick really works."
                }
            };
            await context.Comments.AddRangeAsync(comments);

            // Seed Ratings
            var ratings = new List<Rating>
            {
                new()
                {
                    ShowcaseDesignId = showcaseDesigns[0].Id,
                    UserId = users[1].Id,
                    Value = 5,
                    Review = "Absolutely stunning design! Love the color palette."
                },
                new()
                {
                    ShowcaseDesignId = showcaseDesigns[1].Id,
                    UserId = users[1].Id,
                    Value = 4,
                    Review = "Very peaceful and calming. Great for relaxation."
                },
                new()
                {
                    ShowcaseDesignId = showcaseDesigns[3].Id,
                    UserId = users[0].Id,
                    Value = 5,
                    Review = "Perfect workspace inspiration!"
                }
            };
            await context.Ratings.AddRangeAsync(ratings);

            // Seed Votes
            var votes = new List<Vote>
            {
                new() { PostId = posts[0].Id, UserId = users[1].Id, IsUpvote = true },
                new() { PostId = posts[1].Id, UserId = users[1].Id, IsUpvote = true },
                new() { PostId = posts[2].Id, UserId = users[0].Id, IsUpvote = true }
            };
            await context.Votes.AddRangeAsync(votes);

            await context.SaveChangesAsync();
        }
    }
}
